[package]
name = "sebmalek-com"
version = "0.1.0"
edition = "2021"
publish = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
askama = "0.11.0"

